# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('choice_options', models.CharField(help_text='Coma separated string of all possible variants', max_length=1000)),
                ('correct_answers', models.CharField(help_text='Coma separated string of all correct answers', max_length=1000)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
