# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-13 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='rate',
            new_name='score',
        ),
    ]
